# Site settings
title: It's my blog
email: your-email@domain.com
description: > # Stuff I think might be worth writing about
baseurl: "" # the subpath of your site, e.g. /blog/
url: "blog.dansthe.name" # the base hostname & protocol for your site
twitter_username: null
github_username:  Ivesey

# Build settings
markdown: kramdown

# Customer collections
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/
